### ISSUE TITLE
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

### ISSUE THREAD

**Issue by belo9601bb** [Kardinia-Church/Blackmagic-ATEM-Tally#1]
Hi,
I've installed CCU tally on an ESP32-WROOM-32U. However, after installation and configuration through the serial console, it continues to experience kernel panics.

`ATEM CCU 2 BT By Kardinia Church
Version: 0.60
Build Date: Jul 17 2023

Send anything over serial to open configuration menu............
Starting STA
Connecting to wifi..Connected! IP address: 192.168.100.224
Attempting connection to the ATEM @ 192.168.100.240.Success!
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x400e164d  PS      : 0x00060930  A0      : 0x800d2b59  A1      : 0x3ffe2520  
A2      : 0x3ffe253c  A3      : 0x00000054  A4      : 0x00008a8f  A5      : 0x0000005e  
A6      : 0x00008a00  A7      : 0x43ff1d4e  A8      : 0x800e164a  A9      : 0x3ffe2500
A10     : 0x3ffedf74  A11     : 0x00000000  A12     : 0x3ffedaf4  A13     : 0x3ffe2550  
A14     : 0x1a8a8f2a  A15     : 0x1a8a8f2a  SAR     : 0x0000001d  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x000000bc  LBEG    : 0x40090ee8  LEND    : 0x40090efe  LCOUNT  : 0x00000000  

Backtrace: 0x400e164a:0x3ffe2520 0x400d2b56:0x3ffe2570 0x400e1171:0x3ffe25b0 0x400de4a6:0x3ffe26a0 0x40114595:0x3ffe26f0 0x40114b81:0x3ffe2710 0x4013e59d:0x3ffe2730 0x4013e533:0x3ffe2750

ELF file SHA256: add49770dea1039a

Rebooting...`

 Do you have any ideas on how to resolve this issue?
 Thank you in advance

**Comment by haydendonald** [comment]
> Hi,
> 
> I've installed CCU tally on an ESP32-WROOM-32U. However, after installation and configuration through the serial console, it continues to experience kernel panics.
> 
> 
> 
> `ATEM CCU 2 BT By Kardinia Church
> 
> Version: 0.60
> 
> Build Date: Jul 17 2023
> 
> 
> 
> Send anything over serial to open configuration menu............
> 
> Starting STA
> 
> Connecting to wifi..Connected! IP address: 192.168.100.224
> 
> Attempting connection to the ATEM @ 192.168.100.240.Success!
> 
> Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
> 
> 
> 
> Core  0 register dump:
> 
> PC      : 0x400e164d  PS      : 0x00060930  A0      : 0x800d2b59  A1      : 0x3ffe2520  
> 
> A2      : 0x3ffe253c  A3      : 0x00000054  A4      : 0x00008a8f  A5      : 0x0000005e  
> 
> A6      : 0x00008a00  A7      : 0x43ff1d4e  A8      : 0x800e164a  A9      : 0x3ffe2500
> 
> A10     : 0x3ffedf74  A11     : 0x00000000  A12     : 0x3ffedaf4  A13     : 0x3ffe2550  
> 
> A14     : 0x1a8a8f2a  A15     : 0x1a8a8f2a  SAR     : 0x0000001d  EXCCAUSE: 0x0000001c  
> 
> EXCVADDR: 0x000000bc  LBEG    : 0x40090ee8  LEND    : 0x40090efe  LCOUNT  : 0x00000000  
> 
> 
> 
> 
> 
> Backtrace: 0x400e164a:0x3ffe2520 0x400d2b56:0x3ffe2570 0x400e1171:0x3ffe25b0 0x400de4a6:0x3ffe26a0 0x40114595:0x3ffe26f0 0x40114b81:0x3ffe2710 0x4013e59d:0x3ffe2730 0x4013e533:0x3ffe2750
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ELF file SHA256: add49770dea1039a
> 
> 
> 
> Rebooting...`
> 
> 
> 
> 
> 
>  Do you have any ideas on how to resolve this issue?
> 
>  Thank you in advance

Hi @belo9601bb sorry for the problem, this project can be a little buggy sometimes.

I am no longer able to work on this project but I can give you some tips as to what could be wrong.

I have seen this problem before. Are you using bluetooth at all? If so I believe there was a problem with the esp32 library, that being that newer versions don’t play nice for some reason.. 

I’m sorry that I can’t help you further with this, but I’ll continue to help where I can!

Thanks!

**Comment by belo9601bb** [comment]
Hi,
Thank you for the feedback.
I was testing the board without the external antenna (I think it crashes if it can't find any device).
With the antenna installed, it's working.
For reference, I'm building with: platform = espressif32@3.0.0.

**Comment by haydendonald** [comment]
Ah, i realise the problem now.
Are you using the direct ATEM connection by any chance or are you going via NodeRed or the server?

I never finished the direct ATEM connection (it was a nice thing to have), so that would explain why it could be crashing on you.

**Comment by belo9601bb** [comment]
Yes, I'm using a direct ATEM connection. It seems to work fine, except sometimes the ATEM connection times out.

I've tried using Node-RED (on windows, on docker it kills the container, i will try with a stronger cpu), and I see that the last commit of the library is version 2.3.0, but Node-RED installs version 2.2.8. After importing the flow and changing the ATEM IP, it successfully connects after some flow restart.  (I'm using an ATEM 2 M/E Constellation HD). when I'm able to get the atem connected i see very high cpu usage on node, and 13mb/s from atem to node, are those value normal?

I setted up the node connection from the tally and it keeps spamming this and ccu/tally is not working:
`Disconnected from Tally Server Sending A Subscribe Request
Disconnected from CCU Server Sending A Subscribe Request`
and the atem get disconnected from node-red, I don't know if it's related or just coincidence. 

Maybe i can try with an older version of nodered?

**Comment by haydendonald** [comment]
> Yes, I'm using a direct ATEM connection. It seems to work fine, except sometimes the ATEM connection times out.
> 
> I've tried using Node-RED (on windows, on docker it kills the container, i will try with a stronger cpu), and I see that the last commit of the library is version 2.3.0, but Node-RED installs version 2.2.8. After importing the flow and changing the ATEM IP, it successfully connects after some flow restart. (I'm using an ATEM 2 M/E Constellation HD). when I'm able to get the atem connected i see very high cpu usage on node, and 13mb/s from atem to node, are those value normal?
> 
> I setted up the node connection from the tally and it keeps spamming this and ccu/tally is not working: `Disconnected from Tally Server Sending A Subscribe Request Disconnected from CCU Server Sending A Subscribe Request` and the atem get disconnected from node-red, I don't know if it's related or just coincidence.
> 
> Maybe i can try with an older version of nodered?

*Oh interesting, didn't think i had the direct connection even near complete..
* NodeRed changed it so i have to click "check for update".. I have clicked that button v2.3.0 is on the pallet now :/
* There is a problem with the Constellation where it spams out multiview packets which is not very friendly.. v2.3.0 of [blackmagic-atem-nodered](https://github.com/haydendonald/blackmagic-atem-nodered/commit/2a9b65865eb81489f9db37b13c32fe4a6bdc6338) fixes this issue (by ignoring them), but the direct connection may still have issues with this
* If the `Disconnected from Tally Server Sending A Subscribe Request Disconnected from CCU Server Sending A Subscribe Request` is while using NodeRed v2.3.0 should fix that issue (hopefully) nodered would crash due to the high amount of packets coming from the switcher

Thanks :)

**Comment by belo9601bb** [comment]
Today, I tested with an ATEM Mini (I will try with the Constellation tomorrow), and it seems to work well. However, I have encountered an issue with the Pocket 6K Pro camera. While it works with the URSA G2 and allows me to modify gain, shutter, and balance, I noticed that gamma, lift, and all color-related features are not working.  Do you thinkBlackmagic may have changed the bluetooth code?
